name: build
on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest ]
        bazel: [ "5.0.0" ]
        java: [ 11 ]
    runs-on: ${{ matrix.os }}
    name: OS ${{ matrix.os }} bazel ${{ matrix.bazel }} java ${{ matrix.java }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
      - uses: docker-practice/actions-setup-docker@v1
      - name: Set Bazel Version ${{ matrix.bazel }}
        run: |
          echo ${{ matrix.bazel }} > .bazelversion
      - name: Build
        run: |
          ./bazelw build //...
      - name: Run binary
        run: |
          ./bazelw run //:binary
      - name: Run image
        run: |
          ./bazelw run //:image
